### ISSUE TITLE
Resolve sorl dependency

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/django-pageblocks#5]
At some point we need to figure out how to either:
- Replace sorl with what it's been renamed to: [`sorl-thumbnail`](https://pypi.python.org/pypi/sorl-thumbnail). This would involve updating from our sorl 3.1 to at least sorl-thumbnail 3.2.x. _(Keep in mind: "the newer sorl thumbnail is essentially a completely different library that bears very little resemblance to the old version")_
- Or, remove the dependency to sorl/sorl-thumbnail altogether by just using a Django [`ImageField`](https://docs.djangoproject.com/en/1.7/ref/models/fields/#imagefield) in the `ImageBlock` and `ImagePullQuoteBlock`.

Either of these options will be tricky since we should migrate the old column's data to the new field format.

**Comment by sdreher** [comment]
The old sorl thumbnail templatetag also does not support saving to an alternate storage system like S3. What about a SimpleImageBlock that houses an ImageField, caption and extra_css (for style & size)? The only downside might be errant large file uploads that inadvertently slow down the system.

**Comment by nikolas** [comment]
I like the `SimpleImageBlock` idea, using django's `ImageField`.

Our existing sorl-ified `ImageBlock` is still vulnerable to large file uploads. At least on my computer, nginx prevents this by returning a "413 Request Entity Too Large" error, when I tried to upload a 1.3MB image.

**Comment by sdreher** [comment]
okay - I started playing with a SimpleImageBlock in meaningfulconsent, see https://github.com/ccnmtl/meaningfulconsent/blob/master/meaningfulconsent/main/models.py#L265. This is working in staging & production. If it seems good, I can move it out into a separate library.

**Comment by nikolas** [comment]
As far as what direction we should take things, I propose we:

* rename `ImageBlock` to `SorlImageBlock` (making it obvious that this block depends on sorl, and will eventually be phased out).
* make a new `ImageBlock` using django's `ImageField`. Thumbnail functionality can be added as needed, and eventually maintained in a separate pageblock like `ThumbnailedImageBlock`.
* `ThumbnailedImageBlock` can save the original size (possibly with specified max dimensions), and maybe 'medium' and 'small' thumbnails. It should be fine for most cases, since those thumbnails can be scaled down with html `width`/`height` attributes, and with CSS.

This is just a brainstorm -- let me know if you have any suggestions. My primary point is, I think that `ImageBlock` should refer to the simplest possible implementation of this block, with no dependencies outside Django.

**Comment by sdreher** [comment]
Noting: The issue with renaming ImageBlock to SorlImageBlock is that it kills any backwards compatibility. Many of our old applications are using the existing ImageBlock, and we're unlikely to have the time/desire to go back and migrate them.

The first step is probably be to move the existing ImageBlock out of django-pageblocks and into its own library package. That should allow us a cleaner migration path whatever direction is taken.

**Comment by nikolas** [comment]
I've made a new repo where I'll put the sorl ImageBlock here: https://github.com/ccnmtl/django-sorlimageblock  So we can eventually remove ImageBlock from this package.
